// v0.2.50: replace `wp config create` shell-out with a native Go
// writer for wp-config.php.
//
// Why: wp-cli 2.10+ has a phar-template loader bug that breaks
// `wp config create` on some PHP combos. We were silently inheriting
// the upstream bug; users got "wp config create failed: phar error"
// with no recourse but to hand-write the file.
//
// What this file owns:
//   - Fetch salts from api.wordpress.org (the canonical source — same
//     URL wp-cli uses internally).
//   - Render wp-config.php from a Go text/template.
//   - Atomic write into docroot, chown to site user.
//
// What's intentionally NOT here:
//   - "Pretty" formatting of the constants — we emit one-per-line
//     define() calls matching wp-cli's output for consistency.
//   - Locale defines (WPLANG / WP_LANG) — set elsewhere by `wp core install`
//   - debug mode toggles — operators flip these via the panel's
//     Vhost-tab freeform settings or by editing wp-config.php directly.
package wpinstall

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/auracp/auracp/internal/system"
)

// saltsURL is wp-cli's source for cryptographic salts. The endpoint
// returns 8 ready-to-paste define() statements (~600 bytes of PHP).
const saltsURL = "https://api.wordpress.org/secret-key/1.1/salt/"
const saltsTimeout = 8 * time.Second

// wpConfigTemplate is rendered into <docroot>/wp-config.php. Mirrors
// the wp-cli config-command template at parity with one cosmetic
// difference: we don't emit comments tied to wp-cli's mustache helper
// (e.g. {{#if}} blocks for optional WPLANG). All eight salts come from
// {{.Salts}} as a verbatim PHP block.
const wpConfigTemplate = `<?php
/**
 * The base configuration for WordPress
 *
 * Generated by auraCP {{.PanelVersion}} on {{.GeneratedAt}}.
 * Edit by hand or via the panel's File Manager → wp-config.php.
 *
 * @link https://wordpress.org/documentation/article/editing-wp-config-php/
 * @package WordPress
 */

// ** Database settings ** //
define( 'DB_NAME',     '{{.DBName}}' );
define( 'DB_USER',     '{{.DBUser}}' );
define( 'DB_PASSWORD', '{{.DBPass}}' );
define( 'DB_HOST',     '{{.DBHost}}' );
define( 'DB_CHARSET',  'utf8mb4' );
define( 'DB_COLLATE',  '' );

/**#@+
 * Authentication unique keys and salts.
 *
 * Change these to any random strings to invalidate all existing cookies.
 * You can generate new ones via https://api.wordpress.org/secret-key/1.1/salt/
 */
{{.Salts}}
/**#@-*/

/**
 * WordPress database table prefix.
 */
$table_prefix = '{{.DBPrefix}}';

/**
 * For developers: WordPress debugging mode. Off by default in production.
 */
define( 'WP_DEBUG', false );

/* That's all, stop editing! Happy publishing. */

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';
`

// wpConfigData is the template view. PanelVersion + GeneratedAt are
// purely informational for the comment header; the meaningful fields
// are DB* and Salts.
type wpConfigData struct {
	PanelVersion string
	GeneratedAt  string
	DBName       string
	DBUser       string
	DBPass       string
	DBHost       string
	DBPrefix     string
	Salts        string
}

// writeWPConfig renders wp-config.php with the given DB credentials
// and writes it to <docroot>/wp-config.php, owned by siteUser. If the
// file already exists it returns nil (idempotent — operators may have
// hand-edited it).
func writeWPConfig(ctx context.Context, r *system.Runner, docroot, siteUser string, s Spec) error {
	target := filepath.Join(docroot, "wp-config.php")
	if _, err := os.Stat(target); err == nil {
		// Already present — don't clobber operator edits.
		return nil
	}

	salts, err := fetchSalts(ctx)
	if err != nil {
		// Network failure shouldn't block install — fall back to
		// locally-generated salts. They're equally secure but they
		// invalidate any external cookies signed before this point
		// (which doesn't matter on a fresh install).
		salts = localSalts()
	}

	data := wpConfigData{
		PanelVersion: "0.2.50",
		GeneratedAt:  time.Now().UTC().Format(time.RFC3339),
		DBName:       s.DBName,
		DBUser:       s.DBUser,
		DBPass:       s.DBPass,
		DBHost:       s.DBHost,
		DBPrefix:     "wp_",
		Salts:        strings.TrimSpace(salts),
	}

	tmpl, err := template.New("wp-config").Parse(wpConfigTemplate)
	if err != nil {
		return fmt.Errorf("parse wp-config template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("render wp-config: %w", err)
	}

	// Atomic write to a temp file then rename — avoids a half-written
	// wp-config from a crashed daemon being observed by PHP-FPM.
	tmp := target + ".new"
	if err := os.WriteFile(tmp, buf.Bytes(), 0o640); err != nil {
		return fmt.Errorf("write wp-config tmp: %w", err)
	}
	if err := os.Rename(tmp, target); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("rename wp-config into place: %w", err)
	}

	// chown to <user>:<user>. PHP-FPM runs as the site user so this
	// is what it'll read; nginx is www-data and doesn't need to read
	// wp-config.php (only the PHP files it fastcgi_passes to do).
	if _, err := r.Run(ctx, "chown", siteUser+":"+siteUser, target); err != nil {
		return fmt.Errorf("chown wp-config: %w", err)
	}
	return nil
}

// fetchSalts asks wordpress.org for a fresh batch of cryptographic
// salts. Returns the verbatim PHP block (8 define() lines).
func fetchSalts(ctx context.Context) (string, error) {
	dlCtx, cancel := context.WithTimeout(ctx, saltsTimeout)
	defer cancel()

	req, err := http.NewRequestWithContext(dlCtx, "GET", saltsURL, nil)
	if err != nil {
		return "", err
	}
	req.Header.Set("User-Agent", "auracp/0.2.50 (wpinstall)")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return "", fmt.Errorf("salt service returned HTTP %d", resp.StatusCode)
	}
	body, err := io.ReadAll(io.LimitReader(resp.Body, 4096))
	if err != nil {
		return "", err
	}
	out := string(body)
	// Sanity: response should start with `define( 'AUTH_KEY'`.
	if !strings.Contains(out, "AUTH_KEY") {
		return "", fmt.Errorf("salt service returned unexpected payload (no AUTH_KEY)")
	}
	return out, nil
}

// localSalts generates the same eight define() lines as wp-cli's
// fallback path. 64 random hex bytes per key — same entropy class as
// the wordpress.org salts. Used when the salt service is unreachable.
func localSalts() string {
	keys := []string{
		"AUTH_KEY", "SECURE_AUTH_KEY", "LOGGED_IN_KEY", "NONCE_KEY",
		"AUTH_SALT", "SECURE_AUTH_SALT", "LOGGED_IN_SALT", "NONCE_SALT",
	}
	var b strings.Builder
	for _, k := range keys {
		buf := make([]byte, 32) // 64 hex chars
		_, _ = rand.Read(buf)
		fmt.Fprintf(&b, "define( '%s', '%s' );\n", k, hex.EncodeToString(buf))
	}
	return b.String()
}
