// Package creator implements the single transactional pipeline that
// provisions every artifact for one site: the Linux user, the docroot,
// the FPM pool / systemd unit, the nginx vhost, the SSL cert files, the
// logrotate config, the chown/chmod recurse. Every artifact is derived
// from one Spec → one in-memory processor.SiteContext → one ordered
// run through the type-specific Creator. There is no path by which the
// vhost can reference a different `user` than the FPM pool: both read
// from Spec.User at the same call site.
//
// Architecture borrows from CloudPanel's PhpSite\Creator (decoded from
// the cloudpanel.deb at /tmp/clp/extracted/...), simplified to match
// auraCP's lighter resource footprint:
//   - No two-server-block dance (single vhost listens 80+443 directly).
//   - Unix socket FPM transport (not TCP loopback) — version-independent
//     path, no port allocator needed for PHP.
//   - One nginx reload per pipeline run (not one per step).
//   - Structured slog at every step (post-mortem grep on domain name).
//
// See docs/CLOUDPANEL-STUDY.md for the full architectural rationale
// and the per-step trace against CloudPanel's source.
package creator

import (
	"github.com/auracp/auracp/internal/paths"
	"github.com/auracp/auracp/internal/webserver/processor"
)

// Spec is the API-side input to a site create. Populated from the HTTP
// request body in internal/api/sites.go::createSite, then handed to
// RunCreate. Every downstream artifact derives from these fields — the
// drift-impossibility property depends on the API layer being the ONLY
// thing that writes to Spec.
type Spec struct {
	// ─── universal ───
	Type     string // "php" | "wordpress" | "nodejs" | "python" | "static" | "reverseproxy"
	Domain   string // e.g. "a.garuda.sh"
	User     string // Linux user, e.g. "a-ukfs"
	Password string // initial SFTP / SSH password (optional; empty = generated by osuser)
	Settings string // operator's freeform nginx fragment for the {{settings}} placeholder

	// ─── PHP / WordPress only ───
	PHPVersion string // "8.3" — must match an installed phpruntime

	// ─── Node.js only ───
	NodeVersion string // pinned Node runtime, "" or "default" → managed default
	StartFile   string // e.g. "index.js", "app.js" — entry point for the systemd unit
	UsePM2      bool   // run via pm2-runtime (still under systemd, not the PM2 daemon)

	// ─── Python only ───
	Module string // e.g. "myapp.wsgi:application" for gunicorn

	// ─── Node + Python share ───
	AppPort int // 0 → allocator picks one; non-zero → use this port verbatim (rare)

	// ─── Reverse Proxy only ───
	Upstream string // user-supplied upstream URL (preserves scheme)

	// ─── WordPress auto-install bundle ───
	// When WPInstall=true and Type="wordpress", RunCreate calls
	// wpinstall.Install after the site is up. Credentials must be
	// pre-provisioned by the API handler (so it can return useful
	// per-step errors); we just consume them here.
	WPInstall    bool
	WPDBName     string
	WPDBUser     string
	WPDBPass     string
	WPTitle      string
	WPAdminUser  string
	WPAdminPass  string
	WPAdminEmail string
}

// RenderContext builds the processor.SiteContext that the renderer needs.
// certPath and keyPath are passed separately because they're tracked in
// a different table (the certificates store) and the Creator pipeline
// runs before the cert is issued (so they're empty on first create) and
// the renewal goroutine re-renders the vhost once lego writes the cert
// files.
func (s *Spec) RenderContext(certPath, keyPath string) *processor.SiteContext {
	ctx := &processor.SiteContext{
		Type:     s.Type,
		Domain:   s.Domain,
		User:     s.User,
		DocRoot:  paths.DocRoot(s.User, s.Domain),
		LogDir:   paths.LogDir(s.User),
		CertPath: certPath,
		KeyPath:  keyPath,
		Settings: s.Settings,
	}
	switch s.Type {
	case "php", "wordpress":
		ctx.PHPVersion = s.PHPVersion
		ctx.FPMSocket = paths.PHPSocket(s.Domain)
	case "nodejs", "python":
		ctx.AppPort = s.AppPort
	case "reverseproxy":
		ctx.ReverseProxyURL = s.Upstream
	}
	return ctx
}
